config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sending_messages.urls", namespace="sending_messages")),
    path("", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sending_messages/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from sending_messages.apps import SendingMessagesConfig
from sending_messages.views import (AttemptMailingListView, InfoTemplateView, MailingDeleteView, MailingDetailView,
                                    MailingsActiveListView, MailingsListView, MailingTemplateView, MailingUpdateView,
                                    MessageCreateView, MessageDeleteView, MessageDetailView, MessageListView,
                                    MessageUpdateView, RecipientCreateView, RecipientDeleteView, RecipientDetailView,
                                    RecipientListFormView, RecipientListView, RecipientUpdateView, SendingCreateView,
                                    SendMailingView)

app_name = SendingMessagesConfig.name

urlpatterns = [
    path("home/", MailingTemplateView.as_view(), name="home"),
    path("info/", InfoTemplateView.as_view(), name="info"),
    path("mailing/add_message/", MessageCreateView.as_view(), name="add_message"),
    path("mailing/add_recipient/", RecipientCreateView.as_view(), name="add_recipient"),
    path("mailing/add_recipient_list/", RecipientListFormView.as_view(), name="add_recipient_list"),
    path("mailing/add_sending/", SendingCreateView.as_view(), name="add_sending"),
    path("mailings/", MailingsListView.as_view(), name="mailings_list"),
    path("mailings_active/", MailingsActiveListView.as_view(), name="mailings_active_list"),
    path("recipients/", RecipientListView.as_view(), name="recipient_list"),
    path("mailing/<int:pk>/", cache_page(60)(MailingDetailView.as_view()), name="mailing_detail"),
    path("recipient/<int:pk>/", cache_page(60)(RecipientDetailView.as_view()), name="recipient_detail"),
    path("message/<int:pk>/edit/", MessageUpdateView.as_view(), name="edit_message"),
    path("recipient/<int:pk>/edit/", RecipientUpdateView.as_view(), name="edit_recipient"),
    path("mailing/<int:pk>/edit/", MailingUpdateView.as_view(), name="edit_mailing"),
    path("mailings/<int:pk>/send/", SendMailingView.as_view(), name="send"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("recipient/<int:pk>/delete/", RecipientDeleteView.as_view(), name="recipient_delete"),
    path("messages/", MessageListView.as_view(), name="message_list"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("message/<int:pk>/", cache_page(60)(MessageDetailView.as_view()), name="message_detail"),
    path("attempts/", AttemptMailingListView.as_view(), name="attempt_list"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.forms import CustomAuthenticationForm, CustomPasswordResetForm, CustomSetPasswordForm
from users.views import (BlockUserView, UnblockUserView, UserCreateView, UserDetailView, UserListView, UserUpdateView,
                         email_verification)

app_name = UsersConfig.name
urlpatterns = [
    path(
        "login/",
        LoginView.as_view(template_name="login.html", authentication_form=CustomAuthenticationForm),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("users/email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset.html",
            email_template_name="password_reset_email.html",
            success_url="/password_reset/done/",
            form_class=CustomPasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html",
            success_url="/reset/done/",
            form_class=CustomSetPasswordForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("profile/<int:pk>/", cache_page(60)(UserDetailView.as_view()), name="profile"),
    path("profile/<int:pk>/edit/", UserUpdateView.as_view(), name="edit_user"),
    path("users/", UserListView.as_view(), name="users_list"),
    path("block/<int:pk>/", BlockUserView.as_view(), name="user_block"),
    path("unblock/<int:pk>/", UnblockUserView.as_view(), name="user_unblock"),
]

sending_messages/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BooleanField, ModelForm
from django.utils.translation import gettext_lazy as _

from sending_messages.models import Mailing, Message, Recipient
from sending_messages.services import parser_input_email_list


class StyleFormMixin:
    """Стилизация формы"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs["class"] = "form-check-input"
            else:
                fild.widget.attrs["class"] = "form-control form-control-lg"


class MessageForm(StyleFormMixin, ModelForm):
    """Форма для письма"""

    class Meta:
        model = Message
        fields = ("topic", "body")


class RecipientForm(StyleFormMixin, ModelForm):
    """Форма для получателей"""

    class Meta:
        model = Recipient
        fields = (
            "email",
            "fio",
            "comment",
            "active",
        )

    def clean_emails(self):
        """Проверяет, существует ли email в базе данных"""

        email = self.cleaned_data.get("email")
        if Recipient.objects.filter(email=email).exists():
            raise ValidationError(_("Этот email уже существует."))
        return email


class RecipientListForm(StyleFormMixin, forms.Form):
    """Форма для списка получателей"""

    emails = forms.CharField(
        widget=forms.Textarea, label=_("example@mail.ru, example2@mail.ru, example3@mail.ru"), required=False
    )

    def clean_emails(self):
        """Обработка введённых данных"""
        raw_emails = self.cleaned_data.get("emails")
        if not raw_emails:
            return []
        emails = parser_input_email_list(raw_emails)
        cleaned_emails = []

        for email in emails:
            email = email.strip()  # Убираем лишние пробелы вокруг email

            cleaned_emails.append(email)

        return cleaned_emails


class MailingForm(StyleFormMixin, ModelForm):
    """Форма для рассылки"""

    class Meta:
        model = Mailing
        exclude = ("status", "owner")

    def __init__(self, *args, **kwargs):
        """При создании рассылки, пользователь может выбрать только свои сообщения и получателей"""

        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields["message"].queryset = Message.objects.filter(owner=user)
            self.fields["recipients"].queryset = Recipient.objects.filter(owner=user)

sending_messages/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.cache import patch_cache_control
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, FormView, ListView, TemplateView, UpdateView

from config.settings import EMAIL_HOST_USER
from sending_messages.forms import MailingForm, MessageForm, RecipientForm, RecipientListForm
from sending_messages.mixins import MailingFormMixin
from sending_messages.models import AttemptMailing, Mailing, Message, Recipient
from sending_messages.services import (get_attempt_mailings_for_owner_from_cache,
                                       get_mailings_active_for_owner_from_cache, get_mailings_active_from_cache,
                                       get_mailings_for_owner_from_cache, get_mailings_from_cache,
                                       get_messages_for_owner_from_cache, get_messages_from_cache,
                                       get_recipients_for_owner_from_cache, get_recipients_from_cache,
                                       send_message_yandex)


class InfoTemplateView(TemplateView):
    """Информация о сайте"""

    template_name = "info.html"


class MailingTemplateView(LoginRequiredMixin, TemplateView):
    """Главная страница"""

    template_name = "home.html"

    def get_context_data(self, **kwargs):
        """Передача объекта Mailing в шаблон"""

        context = super().get_context_data()
        context["mailings"] = Mailing.objects.filter(owner=self.request.user).count()
        context["mailings_active"] = Mailing.objects.filter(status="Запущена", owner=self.request.user).count()
        context["recipients"] = Recipient.objects.filter(owner=self.request.user).count()
        context["messages"] = Message.objects.filter(owner=self.request.user).count()
        attempts = AttemptMailing.objects.filter(owner=self.request.user)
        context["attempt_ok"] = sum([attempt.sending_count_ok for attempt in attempts])
        context["attempt_error"] = sum([attempt.sending_count_error for attempt in attempts])
        context["messages_count"] = sum([attempt.count_messages for attempt in attempts])
        return context

    def dispatch(self, request, *args, **kwargs):
        """Клиентское кэширование"""

        response = super().dispatch(request, *args, **kwargs)
        patch_cache_control(response, max_age=1800)
        return response


class RecipientListView(LoginRequiredMixin, ListView):
    """Список получателей"""

    model = Recipient
    template_name = "recipient_list1.html"
    context_object_name = "recipients"

    def get_queryset(self):
        """Получатели рассылки только текущего пользователя или все получатели в зависимости от прав пользователя"""

        if self.request.user.has_perm("sending_messages.can_view_all_recipients"):
            return get_recipients_from_cache()
        else:
            return get_recipients_for_owner_from_cache(self.request.user.id)

    def dispatch(self, request, *args, **kwargs):
        """Клиентское кэширование"""

        response = super().dispatch(request, *args, **kwargs)
        patch_cache_control(response, max_age=1800)  # Кэширует ответ на пол часа
        return response


class RecipientDetailView(LoginRequiredMixin, DetailView):
    """Информация о получателе"""

    model = Recipient
    template_name = "recipient_detail.html"
    context_object_name = "recipient"

    def dispatch(self, request, *args, **kwargs):
        """Клиентское кэширование"""

        response = super().dispatch(request, *args, **kwargs)
        patch_cache_control(response, max_age=1800)
        return response


class RecipientCreateView(LoginRequiredMixin, CreateView):
    """Создание получателя, устанавливаем владельца получателя"""

    model = Recipient
    form_class = RecipientForm
    template_name = "mailing3.html"
    success_url = reverse_lazy("sending_messages:recipient_list")

    def form_valid(self, form):
        """Сохраняет объект в БД"""

        email = form.cleaned_data["email"]
        recipient, created = Recipient.objects.get_or_create(email=email, owner=self.request.user)
        if created:
            recipient.fio = form.cleaned_data.get("fio", recipient.fio)
            recipient.comment = form.cleaned_data.get("comment", recipient.comment)
            recipient.active = form.cleaned_data.get("active", recipient.active)
            recipient.save()
        else:
            # Если получатель уже существует, добавляем сообщение об ошибке
            form.add_error("email", "Получатель с таким email уже существует.")
            return self.form_invalid(form)

        return super().form_valid(form)


class RecipientListFormView(LoginRequiredMixin, FormView):
    """Добавить список получателей, установка владельца получателей"""

    form_class = RecipientListForm
    template_name = "create_recipient_list.html"
    success_url = reverse_lazy("sending_messages:recipient_list")

    def form_valid(self, form):
        """Сохраняет список получателей в базу данных"""

        emails = form.cleaned_data.get("emails")
        if emails:
            for email in emails:
                if not Recipient.objects.filter(email=email, owner=self.request.user).exists():
                    Recipient.objects.create(email=email, owner=self.request.user)
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование получателя"""

    model = Recipient
    form_class = RecipientForm
    template_name = "mailing3.html"
    success_url = reverse_lazy("sending_messages:recipient_list")

    def get_form_class(self):
        """Редактировать могут владельцы"""

        user = self.request.user
        # если пользователь владелец
        if user == self.object.owner:
            return RecipientForm

        raise PermissionDenied


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление получателя"""

    model = Recipient
    template_name = "recipient_confirm_delete.html"
    success_url = reverse_lazy("sending_messages:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        """Удалять могут владельцы"""

        user = self.request.user
        recipient = self.get_object()
        # если пользователь владелец
        if user == recipient.owner:
            return super().dispatch(request, *args, **kwargs)

        raise PermissionDenied


class MessageListView(LoginRequiredMixin, ListView):
    """Список шаблонов писем"""

    model = Message
    template_name = "message_list.html"
    context_object_name = "messages"

    def get_queryset(self):
        """Сообщения текущего пользователя или сообщения всех пользователей в зависимости от прав пользователя"""

        if self.request.user.has_perm("sending_messages.can_view_all_messages"):
            return get_messages_from_cache()
        else:
            return get_messages_for_owner_from_cache(self.request.user.id)

    def dispatch(self, request, *args, **kwargs):
        """Клиентское кэширование"""

        response = super().dispatch(request, *args, **kwargs)
        patch_cache_control(response, max_age=1800)
        return response


class MessageDetailView(LoginRequiredMixin, DetailView):
    """Информация о письме"""

    model = Message
    template_name = "message_detail.html"
    context_object_name = "message"

    def dispatch(self, request, *args, **kwargs):
        """Клиентское кэширование"""

        response = super().dispatch(request, *args, **kwargs)
        patch_cache_control(response, max_age=1800)
        return response


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Создание сообщения"""

    model = Message
    form_class = MessageForm
    template_name = "mailing2.html"
    success_url = reverse_lazy("sending_messages:message_list")

    def form_valid(self, form):
        """Сохраняет объект в БД"""

        form.instance.owner = self.request.user

        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование письма"""

    model = Message
    form_class = MessageForm
    template_name = "mailing2.html"
    success_url = reverse_lazy("sending_messages:message_list")

    def get_form_class(self):
        """Редактировать могут владельцы"""

        user = self.request.user
        # если пользователь владелец
        if user == self.object.owner:
            return MessageForm

        raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление письма"""

    model = Message
    template_name = "message_confirm_delete.html"
    success_url = reverse_lazy("sending_messages:message_list")

    def dispatch(self, request, *args, **kwargs):
        """Удалять могут владельцы"""

        user = self.request.user
        message = self.get_object()
        # если пользователь владелец
        if user == message.owner:
            return super().dispatch(request, *args, **kwargs)

        raise PermissionDenied


class MailingsListView(LoginRequiredMixin, ListView):
    """Список всех рассылок"""

    model = Mailing
    paginate_by = 10
    template_name = "mailings_list.html"
    context_object_name = "mailings"

    def get_queryset(self):
        """Рассылки только текущего пользователя или всех пользователей в зависимости от прав пользователя"""

        if self.request.user.has_perm("sending_messages.can_view_all_mailings"):
            return get_mailings_from_cache()
        else:
            return get_mailings_for_owner_from_cache(self.request.user.id)

    def get_context_data(self, **kwargs):
        """Пагинация появится, только если рассылок будет больше, чем указано в paginate_by"""
        context = super().get_context_data(**kwargs)

sending_messages/templates/includes/footer.html
<div class="container">
  <footer class="py-3 my-4">
    <hr>
    <p class="text-center text-body-secondary">&copy; 2024 SendingMessages, Inc</p>
  </footer>
</div>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

sending_messages/templates/includes/inc_menu.html
{% load custom_filter %}

<header class="p-3 mb-3 border-bottom">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{% url 'sending_messages:home' %}" class="d-flex align-items-center mb-2 mb-lg-0 link-body-primary text-decoration-none">
          <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
  <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1zm13 2.383-4.708 2.825L15 11.105zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741M1 11.105l4.708-2.897L1 5.383z"/>
</svg>
            <h2>SendingMessages</h2>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'sending_messages:message_list' %}" class="nav-link px-2 link-body-emphasis"><h1 class="display-6">Письма</h1></a></li>
            <li><a href="{% url 'sending_messages:recipient_list' %}" class="nav-link px-2 link-body-emphasis"><h1 class="display-6">Получатели</h1></a></li>
          <li><a href="{% url 'sending_messages:mailings_list' %}" class="nav-link px-2 link-body-emphasis"><h1 class="display-6">Рассылки</h1></a></li>
            {% if not user|has_group:"Менеджеры" %}
          <li><a href="{% url 'sending_messages:attempt_list' %}" class="nav-link px-2 link-body-emphasis"><h1 class="display-6">Статистика</h1></a></li>
            {% else %}
            <li><a href="{% url 'users:users_list' %}" class="nav-link px-2 link-body-emphasis"><h1 class="display-6">Пользователи</h1></a></li>
            {% endif %}
            <li><a href="{% url 'sending_messages:info' %}" class="nav-link px-2 link-body-emphasis"><h1 class="display-6">Информация</h1></a></li>
        </ul>



        <div class="dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
              <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
              <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
            </svg>
          </a>
          <ul class="dropdown-menu text-small">
            <li>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-wallet2" viewBox="0 0 16 16">
                  <path d="M12.136.326A1.5 1.5 0 0 1 14 1.78V3h.5A1.5 1.5 0 0 1 16 4.5v9a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 13.5v-9a1.5 1.5 0 0 1 1.432-1.499zM5.562 3H13V1.78a.5.5 0 0 0-.621-.484zM1.5 4a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5z"/>
                </svg>
                Баланс 0₽
            </li>
            <li><a class="dropdown-item" href="#">Пополнить</a></li>
              <li><hr class="dropdown-divider"></li>
              {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:profile' user.pk %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                  <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                </svg>
                Аккаунт (ID: {{ user.id }})
            </a></li>
              {% endif %}
              <li><a class="dropdown-item" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock-history" viewBox="0 0 16 16">
                      <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022zm2.004.45a7 7 0 0 0-.985-.299l.219-.976q.576.129 1.126.342zm1.37.71a7 7 0 0 0-.439-.27l.493-.87a8 8 0 0 1 .979.654l-.615.789a7 7 0 0 0-.418-.302zm1.834 1.79a7 7 0 0 0-.653-.796l.724-.69q.406.429.747.91zm.744 1.352a7 7 0 0 0-.214-.468l.893-.45a8 8 0 0 1 .45 1.088l-.95.313a7 7 0 0 0-.179-.483m.53 2.507a7 7 0 0 0-.1-1.025l.985-.17q.1.58.116 1.17zm-.131 1.538q.05-.254.081-.51l.993.123a8 8 0 0 1-.23 1.155l-.964-.267q.069-.247.12-.501m-.952 2.379q.276-.436.486-.908l.914.405q-.24.54-.555 1.038zm-.964 1.205q.183-.183.35-.378l.758.653a8 8 0 0 1-.401.432z"/>
                      <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0z"/>
                      <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5"/>
                    </svg>
                  История операций
              </a></li>
              <li><a class="dropdown-item" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list-check" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M5 11.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5M3.854 2.146a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708L2 3.293l1.146-1.147a.5.5 0 0 1 .708 0m0 4a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708L2 7.293l1.146-1.147a.5.5 0 0 1 .708 0m0 4a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0"/>
                    </svg>
                  Отчеты
              </a></li>
            <li><hr class="dropdown-divider"></li>
              {% if user.is_authenticated %}
              <li>
              <form method="post" action="{% url 'users:logout' %}" style="display: inline-block;" >
                    {% csrf_token %}
                    <button type="submit" class="btn dropdown-item"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                  <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                </svg>
                Выйти</button>
                </form>
                </li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'users:login' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-left" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0z"/>
                      <path fill-rule="evenodd" d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708z"/>
                    </svg>
                  Войти
            </a></li>
              <li><a class="dropdown-item" href="{% url 'users:register' %}">
                  Регистрация
            </a></li>
              {% endif %}
          </ul>
        </div>
      </div>
  </header>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

sending_messages/templates/includes/pagination.html
<div class="element-center" style="width: 100%;">
<nav aria-label="Page navigation">
  <ul class="pagination pagination-lg">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link podsvetka-paginat" href="?page={{ page_obj.previous_page_number }}">Назад</a>
    </li>
    {% endif %}
      {% for p in page_obj.paginator.page_range %}
        {% if p == page_obj.number %}
          <li class="page-item"><a class="page-link paginat podsvetka-paginat" href="">{{ p }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link podsvetka-paginat" href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link podsvetka-paginat" href="?page={{ page_obj.next_page_number }}">Вперед</a>
    </li>
    {% endif %}
  </ul>
</nav>
  </div>