config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sending_messages.urls", namespace="sending_messages")),
    path("", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.forms import CustomAuthenticationForm, CustomPasswordResetForm, CustomSetPasswordForm
from users.views import (BlockUserView, UnblockUserView, UserCreateView, UserDetailView, UserListView, UserUpdateView,
                         email_verification)

app_name = UsersConfig.name
urlpatterns = [
    path(
        "login/",
        LoginView.as_view(template_name="login.html", authentication_form=CustomAuthenticationForm),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("users/email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset.html",
            email_template_name="password_reset_email.html",
            success_url="/password_reset/done/",
            form_class=CustomPasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html",
            success_url="/reset/done/",
            form_class=CustomSetPasswordForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("profile/<int:pk>/", cache_page(60)(UserDetailView.as_view()), name="profile"),
    path("profile/<int:pk>/edit/", UserUpdateView.as_view(), name="edit_user"),
    path("users/", UserListView.as_view(), name="users_list"),
    path("block/<int:pk>/", BlockUserView.as_view(), name="user_block"),
    path("unblock/<int:pk>/", UnblockUserView.as_view(), name="user_unblock"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Модель пользователя"""

    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone_number = models.CharField(
        max_length=15, verbose_name="Телефон", help_text="Введите номер телефона", blank=True, null=True
    )
    avatar = models.ImageField(
        upload_to="users/avatars/", verbose_name="Аватар", help_text="Загрузите аватар", blank=True, null=True
    )
    country = models.CharField(
        max_length=150, verbose_name="Страна", help_text="Укажите страну", blank=True, null=True
    )
    token = models.CharField(max_length=100, verbose_name="Token", blank=True, null=True)

    # аутентификация будет по email
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm, UserCreationForm

from sending_messages.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Форма регистрации пользователя"""

    class Meta:
        model = User
        fields = ("email", "password1", "password2")
        labels = {
            "password1": "Пароль",
            "password2": "Повторите пароль",
        }


class CustomAuthenticationForm(StyleFormMixin, AuthenticationForm):
    """Форма входа"""

    class Meta:
        model = User
        fields = ("email", "password")
        labels = {
            "password": "Пароль",
        }


class UserUpdateForm(StyleFormMixin, forms.ModelForm):
    """Форма редактирования пользователя"""

    class Meta:
        model = User
        fields = ("avatar", "phone_number", "country")


class CustomPasswordResetForm(StyleFormMixin, PasswordResetForm):
    """Форма для запроса сброса пароля"""

    pass


class CustomSetPasswordForm(StyleFormMixin, SetPasswordForm):
    """Форма для установки нового пароля"""

    pass

users/views.py
import secrets

from django.contrib.auth import login
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserUpdateForm
from users.models import User
from users.services import get_users_from_cache


class UserCreateView(CreateView):
    """Регистрация пользователя"""

    model = User
    form_class = UserRegisterForm
    template_name = "user_form.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        """Подтверждение почты после успешной регистрации"""

        user = form.save()
        # Делаем пользователя неактивным
        user.is_active = False
        # генерируем токен с помощью библиотеки secrets(16 символов)
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        # откуда пришел пользователь
        host = self.request.get_host()
        # генерируем пользователю ссылку для перехода, она отправится пользователю
        url = f"http://{host}/users/email-confirm/{token}/"
        # отправка сообщения
        send_mail(
            subject="Подтверждение почты",
            message=f"Привет, перейди по ссылке для подтверждения почты {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    login(request, user)
    return redirect(reverse("sending_messages:home"))


class UserDetailView(DetailView):
    """Просмотр пользователя"""

    model = User
    template_name = "profile.html"
    context_object_name = "user"


class UserUpdateView(UpdateView):
    """Редактирование пользователя"""

    model = User
    form_class = UserUpdateForm
    template_name = "user_form.html"
    # success_url = reverse_lazy('home')

    def get_success_url(self):
        """Перенаправление пользователя после редактирования данных на личный кабинет"""

        return reverse_lazy("users:profile", kwargs={"pk": self.object.pk})


class UserListView(ListView):
    """Список пользователей"""

    model = User
    template_name = "user_list.html"
    context_object_name = "users"

    def get_queryset(self):

        return get_users_from_cache()


class BlockUserView(View):
    """Блокировка пользователя"""

    def get(self, *args, **kwargs):
        user_id = kwargs.get("pk")
        user = get_object_or_404(User, id=user_id)
        user.is_active = False
        user.save()
        return redirect("users:users_list")


class UnblockUserView(View):
    """Разблокировка пользователя"""

    def get(self, *args, **kwargs):
        user_id = kwargs.get("pk")
        user = get_object_or_404(User, id=user_id)
        user.is_active = True
        user.save()
        return redirect("users:users_list")

users/templates/login.html
{% extends 'base.html' %}
{% block title %}Вход{% endblock %}
{% block content %}
<div class="container text-center">
    <div class="row">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-secondary">
                <h1 class="display-4" style="margin-left: 8%;">Вход</h1>
            </li>
        </ul>
    </div>
</div>
<div class="container element-center mt-5">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-12">
                <div class="card" style="width:30vw;">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        Войти
                    </button>
                </div>
            <a href="{% url 'users:password_reset' %}">Восстановление пароля</a>
        </div>
    </form>
</div>
{% endblock %}

users/templates/password_reset.html
{% extends 'base.html' %}
{% block content %}
<div class="container text-center">
    <div class="row">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-secondary">
                <h1 class="display-4" style="margin-left: 8%;">Восстановление пароля</h1>
            </li>
        </ul>
    </div>
</div>
<div class="container mt-5">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
</div>
{% endblock %}

users/templates/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2>Пароль успешно изменен</h2>
    <p>Ваш пароль был успешно изменен. Теперь вы можете войти в систему.</p>
</div>
{% endblock %}

users/templates/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2>Установите новый пароль</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Установить пароль</button>
    </form>
</div>
{% endblock %}

users/templates/password_reset_done.html
{% extends 'base.html' %}
{% block content %}
<div class="container text-center">
    <div class="row">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-secondary">
                <h1 class="display-4" style="margin-left: 8%;">Письмо отправлено</h1>
            </li>
        </ul>
    </div>
</div>
<div class="container mt-5">
    <h1 class="display-6">Мы отправили вам письмо с инструкциями по восстановлению пароля.</h1>
</div>
{% endblock %}

users/templates/password_reset_email.html
{% load i18n %}

{% blocktrans %}Вы получили это письмо, потому что вы (или кто-то другой) запросили сброс пароля для вашей учетной записи.{% endblocktrans %}

{% trans "Пожалуйста, перейдите по следующей ссылке в течение следующих 48 часов, чтобы завершить процесс сброса пароля:" %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

{% trans "Ваш имя пользователя, если вы его забыли:" %} {{ user.email }}

{% trans "Спасибо за использование нашего сайта!" %}

{% blocktrans %}С уважением,
{{ site_name }} команда SendingMessages{% endblocktrans %}

users/templates/profile.html
{% extends 'base.html' %}
{% block title %}Личный кабинет{% endblock %}

{% block content %}
<div class="container mb-5">
    <div class="row">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-secondary">
                <h1 class="display-4" style="margin-left: 8%;">Личный кабинет</h1>
            </li>
        </ul>
    </div>
</div>
<div class="container">
    <div class="col d-flex justify-content">
        {% if user.avatar %}
<img src="{{ user.avatar.url }}" class="card-img-top" alt="Аватар пользователя" style="width: 40%">
        {% endif %}
    </div>
    <div class="col d-flex justify-content">
<h1 class="display-6 text-primary">Email: </h1><h1 class="display-6">{{ user.email }}</h1>
    </div>
    <div class="col d-flex justify-content">
        {% if user.phone_number %}
<h1 class="display-6 text-primary">Телефон: </h1><h1 class="display-6">{{ user.phone_number }}</h1>
        {% endif %}
    </div>
        <div class="col d-flex justify-content">
        {% if user.country %}
<h1 class="display-6 text-primary">Страна: </h1><h1 class="display-6">{{ user.country }}</h1>
        {% endif %}
    </div>
    <div class="col-md-12 d-flex justify-content-between">
    <a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-primary fs-2 mt-5">Назад</button></a>
                    <a href="{% url 'users:edit_user' user.pk %}"><button type="button" class="btn btn-danger ms-auto fs-2 mt-5">Редактировать</button></a>
    </div>
    </div>
{% endblock %}

users/templates/user_form.html
{% extends 'base.html' %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<div class="container text-center">
    <div class="row">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-secondary">
                {% if user.is_authenticated %}
                <h1 class="display-4" style="margin-left: 8%;">Редактирование профиля</h1>
                {% else %}
                <h1 class="display-4" style="margin-left: 8%;">Регистрация</h1>
                {% endif %}
            </li>
        </ul>
    </div>
</div>
<div class="container mt-5">
    <form method="post" enctype="multipart/form-data" action="{% if user.is_authenticated %}{% url 'users:edit_user' user.pk %}{% else %}{% url 'users:register' %}{% endif %}">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3">
            <label for="{{ field.id_for_label }}" class="form-label text-primary fs-4">{{ field.label }}</label>
            {{ field }}
        {% if field.errors %}
        <div class="text">
            {{ field.errors }}
        </div>
        {% endif %}
            </div>
        {% endfor %}
    <div class="d-flex">
        {% if user.is_authenticated %}
        <button type="submit" class="btn btn-primary ms-auto fs-4">Сохранить</button>
        {% else %}
        <button type="submit" class="btn btn-primary ms-auto fs-4">Зарегистрироваться</button>
        {% endif %}
    </div>
        </form>
</div>
{% endblock %}

users/templates/user_list.html
{% extends 'base.html' %}
{% block title %}Пользователи{% endblock %}

{% block content %}

<div class="container text-center">
    <div class="row">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-secondary">
                <h1 class="display-4" style="margin-left: 8%;">Пользователи</h1>
            </li>
        </ul>
    </div>
</div>

{% if not users %}
<h1 class="display-6 text-center mt-5">Пользователей нет</h1>>
{% endif %}
<div class="container mt-5">
<ul class="list-group">
    {% for user in users %}
                              <li class="list-group-item">
                                  <div class="row">
                                  <div class="col-md-12 d-flex align-items-center">
    <input class="form-check-input-active me-1" type="checkbox" value="" id="recipient-{{ recipient.pk }}" {% if user.is_active %}checked="checked"{% endif %}>
    <label class="form-check-label-primary fs-4 text-primary" for="firstCheckbox">{{ user.email }}</label>
                                      <div class="ms-auto d-flex">
                                      <a href="{% url 'users:user_unblock' user.pk %}" class="me-2"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-check-square" viewBox="0 0 16 16">
  <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
  <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425z"/>
</svg></a>
                    <a href="{% url 'users:user_block' user.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="red" class="bi bi-trash3" viewBox="0 0 16 16">
  <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
</svg></a>
                    </div>
                                  </div>
                                  </div>
                                  </li>
    {% endfor %}
</ul>
</div>
{% endblock %}