config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sending_messages.urls", namespace="sending_messages")),
    path("", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sending_messages/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from sending_messages.apps import SendingMessagesConfig
from sending_messages.views import (AttemptMailingListView, InfoTemplateView, MailingDeleteView, MailingDetailView,
                                    MailingsActiveListView, MailingsListView, MailingTemplateView, MailingUpdateView,
                                    MessageCreateView, MessageDeleteView, MessageDetailView, MessageListView,
                                    MessageUpdateView, RecipientCreateView, RecipientDeleteView, RecipientDetailView,
                                    RecipientListFormView, RecipientListView, RecipientUpdateView, SendingCreateView,
                                    SendMailingView)

app_name = SendingMessagesConfig.name

urlpatterns = [
    path("home/", MailingTemplateView.as_view(), name="home"),
    path("info/", InfoTemplateView.as_view(), name="info"),
    path("mailing/add_message/", MessageCreateView.as_view(), name="add_message"),
    path("mailing/add_recipient/", RecipientCreateView.as_view(), name="add_recipient"),
    path("mailing/add_recipient_list/", RecipientListFormView.as_view(), name="add_recipient_list"),
    path("mailing/add_sending/", SendingCreateView.as_view(), name="add_sending"),
    path("mailings/", MailingsListView.as_view(), name="mailings_list"),
    path("mailings_active/", MailingsActiveListView.as_view(), name="mailings_active_list"),
    path("recipients/", RecipientListView.as_view(), name="recipient_list"),
    path("mailing/<int:pk>/", cache_page(60)(MailingDetailView.as_view()), name="mailing_detail"),
    path("recipient/<int:pk>/", cache_page(60)(RecipientDetailView.as_view()), name="recipient_detail"),
    path("message/<int:pk>/edit/", MessageUpdateView.as_view(), name="edit_message"),
    path("recipient/<int:pk>/edit/", RecipientUpdateView.as_view(), name="edit_recipient"),
    path("mailing/<int:pk>/edit/", MailingUpdateView.as_view(), name="edit_mailing"),
    path("mailings/<int:pk>/send/", SendMailingView.as_view(), name="send"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("recipient/<int:pk>/delete/", RecipientDeleteView.as_view(), name="recipient_delete"),
    path("messages/", MessageListView.as_view(), name="message_list"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("message/<int:pk>/", cache_page(60)(MessageDetailView.as_view()), name="message_detail"),
    path("attempts/", AttemptMailingListView.as_view(), name="attempt_list"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.forms import CustomAuthenticationForm, CustomPasswordResetForm, CustomSetPasswordForm
from users.views import (BlockUserView, UnblockUserView, UserCreateView, UserDetailView, UserListView, UserUpdateView,
                         email_verification)

app_name = UsersConfig.name
urlpatterns = [
    path(
        "login/",
        LoginView.as_view(template_name="login.html", authentication_form=CustomAuthenticationForm),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("users/email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset.html",
            email_template_name="password_reset_email.html",
            success_url="/password_reset/done/",
            form_class=CustomPasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html",
            success_url="/reset/done/",
            form_class=CustomSetPasswordForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("profile/<int:pk>/", cache_page(60)(UserDetailView.as_view()), name="profile"),
    path("profile/<int:pk>/edit/", UserUpdateView.as_view(), name="edit_user"),
    path("users/", UserListView.as_view(), name="users_list"),
    path("block/<int:pk>/", BlockUserView.as_view(), name="user_block"),
    path("unblock/<int:pk>/", UnblockUserView.as_view(), name="user_unblock"),
]

sending_messages/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BooleanField, ModelForm
from django.utils.translation import gettext_lazy as _

from sending_messages.models import Mailing, Message, Recipient
from sending_messages.services import parser_input_email_list


class StyleFormMixin:
    """Стилизация формы"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs["class"] = "form-check-input"
            else:
                fild.widget.attrs["class"] = "form-control form-control-lg"


class MessageForm(StyleFormMixin, ModelForm):
    """Форма для письма"""

    class Meta:
        model = Message
        fields = ("topic", "body")


class RecipientForm(StyleFormMixin, ModelForm):
    """Форма для получателей"""

    class Meta:
        model = Recipient
        fields = (
            "email",
            "fio",
            "comment",
            "active",
        )

    def clean_emails(self):
        """Проверяет, существует ли email в базе данных"""

        email = self.cleaned_data.get("email")
        if Recipient.objects.filter(email=email).exists():
            raise ValidationError(_("Этот email уже существует."))
        return email


class RecipientListForm(StyleFormMixin, forms.Form):
    """Форма для списка получателей"""

    emails = forms.CharField(
        widget=forms.Textarea, label=_("example@mail.ru, example2@mail.ru, example3@mail.ru"), required=False
    )

    def clean_emails(self):
        """Обработка введённых данных"""
        raw_emails = self.cleaned_data.get("emails")
        if not raw_emails:
            return []
        emails = parser_input_email_list(raw_emails)
        cleaned_emails = []

        for email in emails:
            email = email.strip()  # Убираем лишние пробелы вокруг email

            cleaned_emails.append(email)

        return cleaned_emails


class MailingForm(StyleFormMixin, ModelForm):
    """Форма для рассылки"""

    class Meta:
        model = Mailing
        exclude = ("status", "owner")

    def __init__(self, *args, **kwargs):
        """При создании рассылки, пользователь может выбрать только свои сообщения и получателей"""

        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields["message"].queryset = Message.objects.filter(owner=user)
            self.fields["recipients"].queryset = Recipient.objects.filter(owner=user)

sending_messages/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.cache import patch_cache_control
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, FormView, ListView, TemplateView, UpdateView

from config.settings import EMAIL_HOST_USER
from sending_messages.forms import MailingForm, MessageForm, RecipientForm, RecipientListForm
from sending_messages.mixins import MailingFormMixin
from sending_messages.models import AttemptMailing, Mailing, Message, Recipient
from sending_messages.services import (get_attempt_mailings_for_owner_from_cache,
                                       get_mailings_active_for_owner_from_cache, get_mailings_active_from_cache,
                                       get_mailings_for_owner_from_cache, get_mailings_from_cache,
                                       get_messages_for_owner_from_cache, get_messages_from_cache,
                                       get_recipients_for_owner_from_cache, get_recipients_from_cache,
                                       send_message_yandex)


class InfoTemplateView(TemplateView):
    """Информация о сайте"""

    template_name = "info.html"


class MailingTemplateView(LoginRequiredMixin, TemplateView):
    """Главная страница"""

    template_name = "home.html"

    def get_context_data(self, **kwargs):
        """Передача объекта Mailing в шаблон"""

        context = super().get_context_data()
        context["mailings"] = Mailing.objects.filter(owner=self.request.user).count()
        context["mailings_active"] = Mailing.objects.filter(status="Запущена", owner=self.request.user).count()
        context["recipients"] = Recipient.objects.filter(owner=self.request.user).count()
        context["messages"] = Message.objects.filter(owner=self.request.user).count()
        attempts = AttemptMailing.objects.filter(owner=self.request.user)
        context["attempt_ok"] = sum([attempt.sending_count_ok for attempt in attempts])
        context["attempt_error"] = sum([attempt.sending_count_error for attempt in attempts])
        context["messages_count"] = sum([attempt.count_messages for attempt in attempts])
        return context

    def dispatch(self, request, *args, **kwargs):
        """Клиентское кэширование"""

        response = super().dispatch(request, *args, **kwargs)
        patch_cache_control(response, max_age=1800)
        return response


class RecipientListView(LoginRequiredMixin, ListView):
    """Список получателей"""

    model = Recipient
    template_name = "recipient_list1.html"
    context_object_name = "recipients"

    def get_queryset(self):
        """Получатели рассылки только текущего пользователя или все получатели в зависимости от прав пользователя"""

        if self.request.user.has_perm("sending_messages.can_view_all_recipients"):
            return get_recipients_from_cache()
        else:
            return get_recipients_for_owner_from_cache(self.request.user.id)

    def dispatch(self, request, *args, **kwargs):
        """Клиентское кэширование"""

        response = super().dispatch(request, *args, **kwargs)
        patch_cache_control(response, max_age=1800)  # Кэширует ответ на пол часа
        return response


class RecipientDetailView(LoginRequiredMixin, DetailView):
    """Информация о получателе"""

    model = Recipient
    template_name = "recipient_detail.html"
    context_object_name = "recipient"

    def dispatch(self, request, *args, **kwargs):
        """Клиентское кэширование"""

        response = super().dispatch(request, *args, **kwargs)
        patch_cache_control(response, max_age=1800)
        return response


class RecipientCreateView(LoginRequiredMixin, CreateView):
    """Создание получателя, устанавливаем владельца получателя"""

    model = Recipient
    form_class = RecipientForm
    template_name = "mailing3.html"
    success_url = reverse_lazy("sending_messages:recipient_list")

    def form_valid(self, form):
        """Сохраняет объект в БД"""

        email = form.cleaned_data["email"]
        recipient, created = Recipient.objects.get_or_create(email=email, owner=self.request.user)
        if created:
            recipient.fio = form.cleaned_data.get("fio", recipient.fio)
            recipient.comment = form.cleaned_data.get("comment", recipient.comment)
            recipient.active = form.cleaned_data.get("active", recipient.active)
            recipient.save()
        else:
            # Если получатель уже существует, добавляем сообщение об ошибке
            form.add_error("email", "Получатель с таким email уже существует.")
            return self.form_invalid(form)

        return super().form_valid(form)


class RecipientListFormView(LoginRequiredMixin, FormView):
    """Добавить список получателей, установка владельца получателей"""

    form_class = RecipientListForm
    template_name = "create_recipient_list.html"
    success_url = reverse_lazy("sending_messages:recipient_list")

    def form_valid(self, form):
        """Сохраняет список получателей в базу данных"""

        emails = form.cleaned_data.get("emails")
        if emails:
            for email in emails:
                if not Recipient.objects.filter(email=email, owner=self.request.user).exists():
                    Recipient.objects.create(email=email, owner=self.request.user)
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование получателя"""

    model = Recipient
    form_class = RecipientForm
    template_name = "mailing3.html"
    success_url = reverse_lazy("sending_messages:recipient_list")

    def get_form_class(self):
        """Редактировать могут владельцы"""

        user = self.request.user
        # если пользователь владелец
        if user == self.object.owner:
            return RecipientForm

        raise PermissionDenied


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление получателя"""

    model = Recipient
    template_name = "recipient_confirm_delete.html"
    success_url = reverse_lazy("sending_messages:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        """Удалять могут владельцы"""

        user = self.request.user
        recipient = self.get_object()
        # если пользователь владелец
        if user == recipient.owner:
            return super().dispatch(request, *args, **kwargs)

        raise PermissionDenied


class MessageListView(LoginRequiredMixin, ListView):
    """Список шаблонов писем"""

    model = Message
    template_name = "message_list.html"
    context_object_name = "messages"

    def get_queryset(self):
        """Сообщения текущего пользователя или сообщения всех пользователей в зависимости от прав пользователя"""

        if self.request.user.has_perm("sending_messages.can_view_all_messages"):
            return get_messages_from_cache()
        else:
            return get_messages_for_owner_from_cache(self.request.user.id)

    def dispatch(self, request, *args, **kwargs):
        """Клиентское кэширование"""

        response = super().dispatch(request, *args, **kwargs)
        patch_cache_control(response, max_age=1800)
        return response


class MessageDetailView(LoginRequiredMixin, DetailView):
    """Информация о письме"""

    model = Message
    template_name = "message_detail.html"
    context_object_name = "message"

    def dispatch(self, request, *args, **kwargs):
        """Клиентское кэширование"""

        response = super().dispatch(request, *args, **kwargs)
        patch_cache_control(response, max_age=1800)
        return response


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Создание сообщения"""

    model = Message
    form_class = MessageForm
    template_name = "mailing2.html"
    success_url = reverse_lazy("sending_messages:message_list")

    def form_valid(self, form):
        """Сохраняет объект в БД"""

        form.instance.owner = self.request.user

        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование письма"""

    model = Message
    form_class = MessageForm
    template_name = "mailing2.html"
    success_url = reverse_lazy("sending_messages:message_list")

    def get_form_class(self):
        """Редактировать могут владельцы"""

        user = self.request.user
        # если пользователь владелец
        if user == self.object.owner:
            return MessageForm

        raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление письма"""

    model = Message
    template_name = "message_confirm_delete.html"
    success_url = reverse_lazy("sending_messages:message_list")

    def dispatch(self, request, *args, **kwargs):
        """Удалять могут владельцы"""

        user = self.request.user
        message = self.get_object()
        # если пользователь владелец
        if user == message.owner:
            return super().dispatch(request, *args, **kwargs)

        raise PermissionDenied


class MailingsListView(LoginRequiredMixin, ListView):
    """Список всех рассылок"""

    model = Mailing
    paginate_by = 10
    template_name = "mailings_list.html"
    context_object_name = "mailings"

    def get_queryset(self):
        """Рассылки только текущего пользователя или всех пользователей в зависимости от прав пользователя"""

        if self.request.user.has_perm("sending_messages.can_view_all_mailings"):
            return get_mailings_from_cache()
        else:
            return get_mailings_for_owner_from_cache(self.request.user.id)

    def get_context_data(self, **kwargs):
        """Пагинация появится, только если рассылок будет больше, чем указано в paginate_by"""
        context = super().get_context_data(**kwargs)

sending_messages/templates/mailing_ok.html
{% extends 'base.html' %}
{% block title %}Отправка{% endblock %}

{% block content %}
<h1 class="display-6 text-center mt-5">Ваша рассылка успешно отправлена!</h1>
{% endblock %}

sending_messages/templates/mailings_list.html
{% extends 'base.html' %}
{% block title %}Рассылки{% endblock %}

{% block content %}
<div class="container text-center">
    <div class="row">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-secondary">
                <h1 class="display-4" style="margin-left: 8%;">Рассылки</h1>
            </li>
        </ul>
    </div>
</div>
<div class="container">

    {% load custom_filter %}

    {% if not user|has_group:'Менеджеры' %}
<div class="col-md-6">
          <div class="card-body">
            <a href="{% url 'sending_messages:add_sending' %}" class="d-flex align-items-center mb-lg-0 text-decoration-none">
              <button type="button" class="btn btn-primary btn-lg"  style="width: 90%;">+ Создать новую рассылку</button>
            </a>
          </div>
</div>
    {% endif %}
{% if not mailings %}
<h1 class="display-6 text-center mt-5">Рассылок нет</h1>
{% endif %}

<div class="container">
    <div class="row">
<ul class="list-group mt-5" style="margin-bottom: 15%; width: 100%;">
    {% for mailing in mailings %}
    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-success" style="background: DarkGray;">
        <div class="card" style="width: 100%">
            <div class="row g-0">
                <div class="col-md-10">
                    <div class="card-body">
                        <p class="card-text"><small class="text-body-secondary">id: {{ mailing.id }} · {% if not user|has_group:'Менеджеры' %}отправлено {{ mailing.sending_count }} раз{% else %}пользователь-владелец: {{ mailing.owner.email }} {% endif %}</small></p>
                        <a href="{% url 'sending_messages:mailing_detail' mailing.pk %}">
                            {% if mailing.name %}
                        <h5 class="card-title">Рассылка: {{ mailing.name }}</h5>
                            {% else %}
                            <h5 class="card-title">Рассылка: {{ mailing.id }}</h5>
                            {% endif %}
                            </a>
                        <p class="card-text">Дата и время первой отправки: {{ mailing.date_time_first_shipment }}</p>
                        <p class="card-text">Статус рассылки: {{ mailing.status }}</p>
                        <p class="card-text">Тема: {{ mailing.message.topic|truncatechars:100 }}</p>
                        <p class="card-text">Сообщение: {{ mailing.message.body|truncatechars:150 }}</p>
                    </div>
                </div>
                {% if not user|has_group:'Менеджеры' %}
                <div class="col-md-2 element-center">
                    <div class="element-evenly">
                  <a href="{% url 'sending_messages:send' mailing.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-send" viewBox="0 0 16 16">
  <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576zm6.787-8.201L1.591 6.602l4.339 2.76z"/>
</svg></a>
                    <a href="{% url 'sending_messages:edit_mailing' mailing.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
</svg></a>
                    <a href="{% url 'sending_messages:mailing_delete' mailing.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="red" class="bi bi-trash3" viewBox="0 0 16 16">
  <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
</svg></a>
                        </div>
                </div>
                {% endif %}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% if show_pagination %}
<div class="container" style="margin-top: -9%;">
    {% include 'includes/pagination.html' %}
</div>
{% endif %}
</div>
</div>
{% endblock %}

sending_messages/templates/recipient_list1.html
{% extends 'base.html' %}
{% block title %}Получатели{% endblock %}

{% block content %}

{% load custom_filter %}

<div class="container text-center">
    <div class="row">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-secondary">
                <h1 class="display-4" style="margin-left: 8%;">Получатели</h1>
            </li>
        </ul>
    </div>
</div>
{% if not user|has_group:'Менеджеры' %}
<div class="container">
<div class="col-md-6">
          <div class="card-body element-center">
            <a href="{% url 'sending_messages:add_recipient' %}" class="d-flex align-items-center mb-lg-0 text-decoration-none">
              <button type="button" class="btn btn-primary btn-lg"  style="width: 90%;">+ Добавить получателя</button>
            </a>
              <a href="{% url 'sending_messages:add_recipient_list' %}" class="d-flex align-items-center mb-lg-0 text-decoration-none">
              <button type="button" class="btn btn-primary btn-lg"  style="width: 90%;">+ Добавить получателей</button>
            </a>
          </div>
        </div>
    </div>
{% endif %}
{% if not recipients %}
<h1 class="display-6 text-center mt-5">Получателей нет</h1>>
{% endif %}
<div class="container mt-5">
<ul class="list-group">
    {% for recipient in recipients %}
                              <li class="list-group-item">
                                  <div class="row">
                                  <div class="col-md-12 d-flex align-items-center">
    <input class="form-check-input-active me-1" type="checkbox" value="" id="recipient-{{ recipient.pk }}" {% if recipient.active %}checked="checked"{% endif %}>
    <label class="form-check-label fs-4" for="firstCheckbox"><a href="{% url 'sending_messages:recipient_detail' recipient.pk %}">{{ recipient.email }}</a></label>{% if user|has_group:'Менеджеры' %}- пользователь-владелец: {{ recipient.owner.email }}{% endif %}
                                      {% if not user|has_group:'Менеджеры' %}
                                      <div class="ms-auto d-flex">
                    <a href="{% url 'sending_messages:edit_recipient' recipient.pk %}" style="margin-right: 5%;"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
</svg></a>
                    <a href="{% url 'sending_messages:recipient_delete' recipient.pk %}"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="red" class="bi bi-trash3" viewBox="0 0 16 16">
  <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
</svg></a>
                    </div>
                                      {% endif %}
                                  </div>
                                  </div>
                                  </li>
    {% endfor %}
</ul>
</div>
{% endblock %}